### ISSUE TITLE
Synthetics deployment automation - Terraform - AWS

### ISSUE THREAD

**Issue by TedatKentik** [kentik/config-snippets-cloud#28]
We’re wondering how we can run the Kentik Synthetic agent on an EC2.  We’re not sure how to make that agent’s registration survivable across new EC2 instances.  We have a security policy that requires us to upgrade the AMI on all our EC2s every 30 days.  So we need to be able to deploy an agent to an EC2 via Terraform and have it still be the same agent as the previously deployed instance.

Is that possible?

**Comment by TedatKentik** [comment]
AWS Linux does not include Git.  Installing Git, removes the issue when deploying in AWS based Linux nodes.

**Comment by danielfurman** [comment]
@TedatKentik I didn't dive into the task or why this ticket is closed (I believe it shouldn't be), but here is a PR which is a first step for this automation: https://github.com/kentik/config-snippets-cloud/pull/61
